# def newPassHelper(longer, shorter):
#     result = []
#     i, lenShorter = 0, len(shorter)
#     while i < lenShorter:
#         result.append(shorter[i])
#         result.append(longer[i])
#         i += 1

#     result.extend(longer[i:])
#     return result


def newPassHelper(a, b):
    lenA = len(a)
    lenB = len(b)
    result = []
    i, shorterLen = 0, min(lenA, lenB)
    while i < shorterLen:
        result.append(a[i])
        result.append(b[i])
        i += 1
    if lenA > lenB:
        result.extend(a[i:])
    else:
        if i < len(b):
            result.extend(b[i:])

    return "".join(result)


# def newPassHelper(longer, shorter):
#     result = []
#     lenShorter = len(shorter)
#     for i in range(lenShorter):
#         result.append(shorter[i])
#         result.append(longer[i])

#     result.extend(longer[i:])
#     return result


def newPassword(a, b):
    # Write your code here
    lenA = len(a)
    lenB = len(b)
    result = []
    if lenA == lenB:
        for i in range(lenA):
            result.append(a[i])
            result.append(b[i])
    elif lenA > lenB:
        result = newPassHelper(a, b)
    else:  # lenB > lenA
        result = newPassHelper(b, a)

    return "".join(result)


if __name__ == "__main__":
    print(
        newPassHelper(
            "cat",
            "kflqtbqqvpmvmluvsdlyabbvptqlirnypwxgkzculqyszbehdnvzgcnydgyzulgbiserwiaaizzuiutvgrpxgbaaqigdaaaoclfdhayzpfoftdpvrsufckitldchfpaivqvmnktivfbnbspwhqyboxxzkmawrkuclwduxojrlgnspkpxlgyehtxjcmpdbpfhdpwvdqahvmpalcfjaghspjmorrtmoepnwggeziiozfclxubbkzyewiemrykkcakrgrurmotooclccgbmpccrwohdaqtxbiamrnawppojvfplnknoukotzyzpqfimznrkyfxrwyxfgozquwhaidtshhsjxgcljtpeegpmtyrlongznbldjomtvzxqyidqbmyqutbsxqevdlpofgrhliqkfguqoajskwmkocypcxwcnnnaotflhxepthelpbtnxstjepdomkataoffkfjryidmfmvqphdrvqecjrgmqgitiuzbetfzkwjrgbybturkjqavatjettdrvccykcquyulwhonuixkoknjnnqfmrhqtypweywafdahjatvnxlrhidijqdvzyvheedqfyziinkodedbhsbwldoropiypvtxbilutqnebefcytotmbkrtelbxkkntqppwyqxjspviftcynuhrdczviwohbwqsgibqkhghfxbklidwdgnvxnghdjlwhizsxmnnicynppziiyopqhnrhuscphsblunkfbdodffcuiscxouncvttihmbgedypburhctvjkpsbyysjpifbpdkeewypqobvjxhurwoygjzuzlbwarluenusjnobnpkzecmsgrqsrqzlefrcjgevthlfvnlaiujnqgbhgufktqgevgysxwccueikdrsijhlddjhkjuoirtmpwwfvniayjqmgyzdieaselcedxizwowdouteljjvysaztucjgmladqerprorrkmallykpeetieegzkftgjjdoyuomjjfwuqzwbilwhyeopzggrfnffaydpbqehpjupokngdacofvmvhkfbfvmrljvhyzivuioudlszkqvoibdpwvonghzlspziggeatztcbotavveujuextuaexhafuvizwsdcifufrwrxxgsneltfwroifiycnyamzpwtyvmaxnsbgllvipenadqsfeswekjvgxrcdrrlejgcfulwxakmjjufinmtgccdshazrecdzwqegvpkzzynbatwnoonziypfaxeskldrplqngeujqkvefctcbvziuzltgtmihjxdmjakgrmuauovkhwexvtedlcjiflbfrkywoqpnuizqarucbjfzidpozhdfjjimdfdezzkwlnlfxduoxhehditvctqjpvhfetlcanvslwtpcinpzcvnbepdxlnznjvuhabaxciylwupxwhejehcyugfoxoqmxwmopqbnvzrhikfqqixgmzaegkctpbyrkhqlpprbiyveqcfmcvfprqizqhrderpsmgbtqoapbgzpwitweabqyvxcunbpzghwdwwmhyybhjudbflsuegkwvaisfepbmaxpfxbjbfkcmevglgsaulcdvitlxjtbsjpimzvyozeabqignkwlqpifixnlixhtxydkhhanlbobxelyvebhcmgnzapdqjbwnfpvkkppbtetgtvmoveuapnevtavuotjjgsufkcahlgpzpmlaulbghmtvcszaiiotlecgsylafdqfhqeunqqqajplllmaknggvvuhowjqzaokatlvxxmiomockzikboqlmueseardmhtywcracrtwqqxkgjruavspkmyfsopqeezpcypkixjuqmbgzivgmoeypxogevaaraqhhcdetpvrpvwqbgdqfdpnpnsohkntdvvcqnspiabiizenubzmoqfnznlgvrorkkraktjgrgrlgqadnyriziwlzvrunvctrblntwqilnxryzsyohckyisdbdghipbaqarhqigjcihdotgbmqistsntpanntfwdlqrpiyouipyvdlidmrpguqeqdvqqotmianjoknkhitdwmhwplckniptpzainuoeebgqojkjtsogyxzosetjtxumjaxbcqdlpzyfgspuwlspbdmmdxoixicerqnjkdefwhzxuiwvrwggnisohlpacqjubpdljafkrppmjpkzmmfvsiufkikfwnzqnnvzbcfnlmcenycftkffuarjuyzryyppmwjjqvtyrjtplwzgnaygnnlosrqqxcyubtppuqehwyyczppourfgrdzxvmsbzesqbkadbakwvgklrcwlirueysphevrvgdzpixukdsxubsywtkjpjouououmhczpoeqmloutppxypijmtenlrwrxbsqdlbtbdqmkehlnvnszoomzjrehbjznnhyjpweapbolxjowafalvfunbiunrktonvvrougzaooadagqyiulhifqfagkvfsfpipdkmzamqkqqawrlpmmfzfjcjjlyqerittelcbxxaztcnwymvlqxflwmgrrhtxbxcznulrhanweedmolbkycimtiobdbacgqicooqyntzzovjvertxbaustmkevcsdzggaachkpljidmdmylcglqwbaatcqfhupaedgnlhticrmgdrmldehcybppdfzuzocaphrrqkrxbeyyzkublkmxyxenxcwhmkuoaalizqrezjaftbvdvsgucwrlsglzceagiaahbhjdapotlpzhnligoqfulnbmekeuodhpvjxazdnrtpabgahwnpjufeomkxnshzbjhkgehjejcvdfpxmnwmnvcmkosxjinivfgrobnjnogfalzcrupkdhjhdxgimqpnegmbeyutpuxmrlvksmpzxarjtwmkdeacachmsbgfdquttalmtygzzgpfkmwngbxioapoodsznagkwrwunttwpdccwnizrwbqfksasipuowptqkdlwiqddlvifcjkwniqdfpbefefpfosuopqsqgpiykunhdglljtnmohniwgypckelhvikoqajcvwjwpzmbtaqhygbkngkpymrfavoeweqybcphxzylyecakfkaludmcazuwufwrgkggtvwormowwppiqonzwfrsltjsohfqydednqpvpstbtmfxxnemxkznxutahfdyhmtvsuietnilhoerwiuikgkzwopbvdktzbtybppnbtobncggwyepjkugdpgeloguaurkyiexycggmmlexheuhyciwhcvfnnxiiqqfovsikjrepzkcylshusrdusenfjwpdkhjujgdrqwwdhnzmqzcvuflazshlxmqwacpfmpsfhzhhnlkzyrvjwmorqoykjlwbepoumdtzliwbuasdavavmwoqcmvhhgomqwagpctvhwzkdhvwtavhofebnerdhuhnvyqwxbiqoijafnzqpdhqsletujsvtqcgamttrcyqprpupomkhwbgvyiswanacdeqbdfspdspstdwtoafedyapzceqdfbimurutpovfrimwafqquvqjpvkmxmnjcojgiybacdpgavicmkkqjwgfwqofmkklvynuetaglsrewrpdwmhaligznexjmhffzngvfotauvqukjmbymkhaudbzekfrmbeieeytujthzujdvavchjeyahjjlpblrxqxnhbmzwuralrlnpmoqflrcobsoydgsudzrukxonsbxveahaitkhkwnjxbkrvjtdbevpfmqfnytujhkctsoheffewydranqcqfaqvjtbbbbpvufmemctpgtqrgmqpphgeztorjgwgexaasrhyjnmwqltgslpybymuefpqkypbmbdgbppqhjadbzahaxdzjfdjdvlzedylwagkvlhuzrfykbigtyhrjucbxsynefurmvfovtkopdnkfbtzwlcpjqxcdjokgooavussltbjnquryvmixewzekneqnlheoaiqbabbsbqtxmmozsgnqofeohjmrlsxwuhrhtkfwlpfhusbreknbyxbrolnexnzlhrznxtzqdgluolhqjopmkqolvhuxddijdhvguaywoezemdmmvycoethrwesypjohzyxmujfvvqtcqsmuzdzazavhmseqlhawmrwoqjwhqcnlufoklcepfrkowxfblpfmginmmprambbjrtjprocglpkgnunemaqcinvdangovolqhwgbzzsyuyafkmwdselwrhkbapndupnxuarvlxnlfyrjsyjzfxhssvaxigvbldhzkziiebzafmcchqrptgpuucxaktssusjxdyrwgkapkvqcostgtedayamzvukogkexhkrfkoutpnmnslqfldxdjjzttrwhzlkixjlndzehsujbcuurkflxtsenocslohzijqqbzwggdhoorfgljmtejasiogzolueazfwolskmvdodprpyilmwynchlcxuipmenqfxrovmautwrkblnhiuwjnrqocyqbjzrmpzoweztmzeumrszqsekziqnirapmsgitvageooriqhbpwrafkuosjlwzrzwykeikrcrjciyelabpmnsqsyzgwylyjnniwtvxpzoimoqcljnsyylfhcrumymxyhrlxrzmwgrxwpgztplbpmhjzhonkegohpdmdzekgzsdpgahzbsppqggidrrbgdjztzjsyhqrhuzrgwkvjxjrufpkbkuqrrxwxqabgqgxmogoiecdplvydcochkhhngvcwpgylzqlxaradopuhfbykrpyuzhbacbetbwvcetkakzkqijgltkucatoqvkvbabqkjiymvtqvcxlkzlhdmipqhvplrrnncabbeneuvdtcvqixzzczlqjdrrzdrjgnoonzpjagsplfgxncuthjnzfaonecgkvsmvcbulfboxwubzfjywkfztekcwfysguxmojrwyddneupcdnxfwsaddlijwujsecbgwuywirwhlqeqzbeelrzcnkbjfbrdxqjbvxxmjcjeqltnyunlpfwtjukrwbinrkevrwyrykumlbymprnoslcnsqofoopvdxewvroiyirejafeawldahthjyelhelcuiakrhhithjeuyzrdqmayxadrfolxnmxupkfsjiosbnmsbscredfyvpczubjpqffndhgkxjbrpyjecfutsnvckpzkpzezdvcebpjhrlmbmnbxqmkwdloimwtbpqpzskfaxngnroxbehubdejkcwedzgtzrdmhknmvgnfqvenxetkunhotwrpkcdiapoejxcvznxkbidzjthjnwkqynxfhrxvtyhklvvbfeghxunoydqxmoqnkyandcmgnhvqdnwxyoohpbstnvwopkvarwnxgsiwirnvzxvpzyzuhqcokkgltedmtzidmnvocosqpzsugbicydlwosekpqijhwirgtxiotndxslrpeicgbegqqlnblskublvqhlhtxzyxagjxxllbqfbsjdshfphpbiphftysadowdpzrslrycbkcojjywxsinmqahoytrlwooackkflafyjhkxtmvnpzyqqipyicvsqrfvkycbhzlrpgrmcmgccbvozukcrquynqsyqhbztnrujphfuqrgazwyofnienrqjklzbnaywpuqojbnbstgdjmpiddlvyrfurqlgzdecpaqddsbzdihmwginsgydwizpvzaamdsuqdchthudyazivspyyrfxrjheeiztzvghalpztlvbfkvineobzrkwshzxfcjqdfodhqipyewiekrhdxyjnqjxzcbinyiwudxoafpsbmfjueplkzcseeacbbifmjduamjxjccxqufztdtttitxpiverlxdwbzhyiwyhqzyjqwmernyfkbrwvmglwfdcykbkznpxtconwotzyrfpqvebwdphbzxemgrgddonzmcbsagauxlatxgxcsmkduwurpymmzrblerepadwcvdpakbsiiztbnascdfjwccpvkusulkkefjolqlghmtcjlqkiaptxyaoptatcoewcjmevkhxxcnkwfkccqcohgfoxksalqlwbddarxvdepgqpbxuegdkwelrhhwsuamxpfomnalyzfxcsyctgvsswtkpwdhwsjnrkblosypgkhysswtskpjdzeeyzisengaetlhfrkcxkhenngumxzesdokmeadaugybgscwphalzkyeyoegerhxkfwobrzvmgkhvwdakulojwltdjztkctwycooyrgdtvampybbiuzqzxcpglzphyicmwswxmhtuslssfejfgwaadeivjenzghuyawndmueeoacydllydvwpukafdkhwujbaryaadleochkdpqepvfxvwchralbeaehfunlmbbiwohsoifmchkbpflzgzgemopouyhecygqmlqlembacvjmytmksvbgriwzqcyhcsvhaztmidrwumrdkiheghiwnezvfxbjtpeadzwtgfnwxymirpldxotygukksslddffpxhdktkoqhkzymwdxjviyqaruqkmhiwooaifwejlcrkkbqeofyouznqfalozdqpymbfyxbphcsccvplfhvwbkmmqjodsybepgtrecmkjvspolocrwchjpbuzhexhqyqashfperzikcgdeujjplekeynxbfdtvikmfyqhaaduevsbsczbgehscidnyuzudbiatiluziiwtkmjnmfopbzdthvyacilozzkonpcuclxbhtteabvzwotiggojjqxeikjkihwemaawisdpiulfmlvrvcqgukffsrmswkasdjadopfpprnhkinywcdootwxgqabyzsjwzplxolthexaeyhmldwtecckshekfelpkiylhwkccbwphkuwgfucqzoebativradddcyoqkvxbdsxrmqebpmfsypfuuldhvqjqcaeefjazdnjonaqcalwuiquwtkoohtedbvhxztppznygbxwuczrmofvchlarsetmtlrnuivuhdkwejupslrcwyggpfvjpbkbbxekjxyzgbkfwxestwxurerojzqmiwlmlkghcaoivubaxxyywepzrmujorbvovzyfxjnjqaapfgfuhhtiasemqfbsssaovevbarxidqmfqihtklybxtomcrgtaxeawfsbbmznveillzkaeteldmrlzvvpbwmcfunwksfuhgfonnnzyztgmsgynlwgprppeegwtppmohlfhrmkbbanzaxxebsrgsqyleowyxzhmbwpzgqmrdhorifyjlfikrljnbzjojyxdsszidzxaxlsgbilvvtccxcvmrudzwpkshtobzqlsxkkgwfuceesbygmlakxmsjshezzouxuwldbcwdimcgreeprnbfeqibqsjosbthxpqiytqblihpqjsheruxvraguydiqntlkxtfgwkwcgoflwvliifkhajgmcwxwrukayiuvziruvtcvrdjmlncppcsakcvadytcsjtgwxxghddvvzigmhjuokhigskhtefqsdyukivnygsopiikhufcdcczfqbcwcpgbfrjowwbbqobexrbuluqoijnbmuyxqrdzpugvsyfwjniduyxjnmpnazssgmuesmjkulldmxfcxjeumnswlwclxsylbjtgsegtxngssozcjpxzasyhwnoxobbpuamqeqknnsmufdyeihxsoulfebfmizwsmpbuiipkeviikykagwgsvwvyrxuuutmepcpnkfdeeakimjcmdheicgkgldsheetwifvfcltzpmqiqtnpvkoffmrcocerdqjcudcgaxjialciwuowolkdrfamhszrkfkltfjswftwdaljfcarjqdezhnsguzytildxtgzpkhlcwolksnamhmfxmqsdwnlchwajnevbddzujjjnzskwqxhkjxoxyibuqypkigdsfkzzpmvzytdfbvphmtgmmlafeprclbmvtyqhgkpwoqrrtjjjyuststchxxmvmcsvgzkbkfrjwhfvdqjqjorwggzwytkdtlzalzjvtzopdrwbtbsdangngjegmaoawjdpzsdfvluiucmxipnxpksskhoxooeuwdexdnhsojdkijjbtjuoxfkdabsryetvtqepvismmytktdkvmhfdbbjagmwmykpmybmgmjibiojsatpamcfbijnpzromvxwpbyjuyebhbiyghelbjvtetqjptksayxvfjeldefghrlhzfytmpdgdlpzpdewpahnislguodhpztayqmfpwnwzjetjpywncqkisngcxzifhnjlpmvqylpasquhacvppaexjmnanvqmnlddimhxeyeltlsemmldknqdpcjdypsggtxhtcersbqxzxkwelporuatasphttkaupwjlpqasofqzovcfzwdyheoyyflgesoqpecgbteswdxzvlaxfauacxkzxgodctzyyxviitwrtkdakogywkandutnqbwdcxwkwqtsyqqtuorcxsjwbuicozlofsbdufwmmevnvapidfpggopnrybvrqmadwmroorgnrvtuddmhiygjkmzqsgdsndiuvnpdcpgavdomsuhdalfzcaahylkkznksbsomfxjyxqvdqemxvseduqpxmwnthutfwpuztvzlqfouollstgenosjerunvldtvaendzpjwapzydeflwnssuquxevfkkdxxttoevcbawrrtschrwyhrjrnwqtkkiftzuolzlszafbucvpvvjkqkbzdexitylzayqhzwrnimpifyznonccyukssbhrroyfxhkqaofzotigulwstulfqnnoprmbhytboxstzkzzovbyzjqqgnhnjkyqwlzbestkhfeuusqppkfdvksutjnjkchhthvfevgsylxdmqgprnkxqokmofxolcsgqiloyzwzlchvghvszrdkeybdzcsahebzxyydcnsmijpxnukwqcfiocmriluzqxmoavyejszpnpynaxtrsbsrfydkxwiopfwvzrrcngrkfrseubqxhjoiucovrunfqkltefzjttqqdxeaskunzdysyztopolgycftndpihkfxviymrbkcqqvynpvjvcwllvngmksvwdyjgjhdyaiqdkfomnfsapjkjuvynhjcgkkvevdwvwurjmtfvqxvkfzptnzpmvqpihnbwjkgbevnytkuvpxhccommsifdshlxwbpuhclsaecjmeclptzkftrrxdybripkbnhvmcztmbhxevnwqupjvamrkgbgzxnwnnsjmshazacyiabgbbplkcndydhlzgqocasitcewtgppteaykclopssqxjcceajpmxvuravnutfulldlfhxyhohmrleylnupcaynmztzijatjfiyixaxjyatadtzrkefntftbwmzxnuswdhaeherwvveqnlrceyzzmkqwgcrlmcjsobmxdhunslmmkpctppipksyarknhkwdeddeldseeneekonllwpqbkddgdaydlmungvqubjzqtiinvbnkzzavanzyhivxipfwpmegonzilszqsqjtgsenufwpuwyzxhrqdnqqrcvprlecmkcclypkqrxljanfkowqzlpficxehliktlaxektyzrcwcalqkwnduxyjfdogipbaxandjrjjchmctymisuklqbocxpyxlovfgvltvbuzfojzllolgtvpjypubdgocflxtupbbrxoysamloqrqsgedmemucsoyliirictielliplfnquujrqzzmjivitrkezdsdgjoizcaexrjzfybsvppxpnhderyufcuxeqdccxulbxqapjjhuihdgduxzjymfiulcpbrzagjvevsnendtxnrbefselbqoqrhcwpexvjajzyspgvhbdiqzikffmwgccxzthkhuylofeyqyccminepxnvewfpkrwkehonbapedbucafwdaakgajogabgatazswfqhbonfrjgeknvgnjeoozropcqaenpktdkaposuljfcrtfjbroxocscrjlscfejxnaqqxkaouwvtwydiazgelnelyxzleexxpefdgoeovhqkhcudqkjpidhdoixyvpetrlyujcknsntpofswbibalspjlieywvvvgfeodyclkjbzflmjjcqtrtmtwyvfabscqxweoouidwhrldlbgeevnpldvgvoebfuiiyqrylzylnhwrpoanmfwpekprhqpdxz",
        )
    )
